version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  ignore:
  - dependency-name: github.com/cloudflare/cloudflare-go
    versions:
    - 0.13.8
